Move usage to the top.

diff --git a/src/run-with-summary b/src/run-with-summary
--- a/src/run-with-summary
+++ b/src/run-with-summary
@@ -1,15 +1,4 @@
-#!/bin/bash
-
-# Customize the success and error messages.
-success_message=${SUCCESS:-"Command executed"}
-error_message=${ERROR:-"Command failed"}
-
-# Print extra stuff like user and hostname in the summary.
-debug=${DEBUG:-""}
-
-# Print the markdown summary after the command output.
-echo_summary=${SUMMARY:-""}
-temp_report_file=${FILE:-"/tmp/summary.md"}
+#!/usr/bin/env bash
 
 usage() {
   cat <<'USAGE'
@@ -35,6 +24,19 @@ Examples:
 
 USAGE
 }
+
+set -e
+
+# Customize the success and error messages.
+success_message=${SUCCESS:-"Command executed"}
+error_message=${ERROR:-"Command failed"}
+
+# Print extra stuff like user and hostname in the summary.
+debug=${DEBUG:-""}
+
+# Print the markdown summary after the command output.
+echo_summary=${SUMMARY:-""}
+temp_report_file=${FILE:-"/tmp/summary.md"}
 
 # Format output into markdown report
 format_output() {
