Alter how the run-with-summary command works: render real-time output, save summary after the fact.

diff --git a/src/run-with-summary b/src/run-with-summary
--- a/src/run-with-summary
+++ b/src/run-with-summary
@@ -12,7 +12,7 @@ Environment variables:
   SUCCESS           Custom success message (default: "Command succeeded").
   ERROR             Custom error message (default: "Command failed").
   DEBUG             If set (non-empty), include User/Host/Directory in the summary.
-  FILE              Markdown report file (default: /tmp/summary.md
+  FILE              The file to append the markdown report to. (default: /tmp/summary.md)
 
 Examples:
   run-with-summary scripts/deploy.sh
@@ -32,36 +32,35 @@ set -e
 
 # Customize the success and error messages.
 command="$@"
-heading_message=${HEADING:-"Command executed"}
+heading=${HEADING:-"Command executed"}
 summary=${SUMMARY:-"Started $(date)"}
-success_message=${SUCCESS:-"Command executed successfully."}
-error_message=${ERROR:-"Command failed"}
-
-# Print extra stuff like user and hostname in the summary.
+success=${SUCCESS:-"Command executed successfully."}
+error=${ERROR:-"Command failed"}
 debug=${DEBUG:-""}
 
-# Print the markdown summary after the command output.
-temp_report_file=${FILE:-"/tmp/summary.md"}
+# Temporary file to store output.
+temp_output_file=$(mktemp)
 
 if [ -z "$command" ]; then
     usage
     exit 1
 fi
 
+format_date() {
+  time="${1:-$(date '+%s')}"
+  format="${2:-+%Y-%m-%d--%H:%M:%S-%Z}"
+  date -d "@$time" "$format" 2>/dev/null || date -r "$time" "$format"
+}
+
 # Format output into markdown report
 format_output() {
-    local command="$1"
-    local exit_code="$2"
-    local start_time="$3"
-    local end_time="$4"
     local duration=$((end_time - start_time))
-    
-    local start_date=$(date -d "@$start_time" '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null || date -r $start_time '+%Y-%m-%d %H:%M:%S %Z')
-    local end_date=$(date -d "@$end_time" '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null || date -r $end_time '+%Y-%m-%d %H:%M:%S %Z')
+    local start_date=$(format_date "$start_time" "+%D %T %Z")
+    local end_date=$(format_date "$end_time" "+%D %T %Z")
 
-    local message="$error_message"
+    local message="$error"
     if [ "$exit_code" -eq 0 ]; then
-        message="$success_message"
+        message="$success"
     fi
 
     echo "| Command    | \`$command\`"
@@ -80,38 +79,24 @@ format_output() {
     echo $message
 }
 
+file=${FILE:-"/tmp/summary.$(format_date).md"}
 
-
-# Record start time
+# Record start time 
 start_time=$(date '+%s')
 
-# Execute command and show output in real time while capturing it
-# Use a temporary file to store output
-temp_output_file=$(mktemp)
-
-if [[ -n ${heading_message} ]]; then
-  echo "# ${heading_message}"
-fi
-
-if [[ -n ${summary} ]]; then
-  echo "${summary}"
-fi
-
-echo "\`\`\`"
-echo "$command"
-echo "\`\`\`"
-echo
-echo "\`\`\`"
-
+# Execute command and pipe output to both terminal and temp file
 set -o pipefail
-$command
-exit_code=${PIPESTATUS[0]}
-echo "\`\`\`"
+$command 2>&1 | tee -a "$temp_output_file"
 
+# Save exit code.
+exit_code=${PIPESTATUS[0]}
+
+# Save end time.
 end_time=$(date '+%s')
 
 # Generate markdown report
-format_output "$command" "$exit_code" "$start_time" "$end_time"
+format_output >> "$file"
+echo "Summary saved to $file"
 
 # Exit same as command.
 exit "$exit_code"
